### ISSUE TITLE
mgcpp::device_vector's move assignment operator behaving weirdly

### ISSUE THREAD

**Issue by mujjingun** [MGfoundation/mgcpp#34]
In `/examples/MLP/MLP.cpp` I'm currently writing, after executing [line 40](https://github.com/MGfoundation/mgcpp/blob/d73f80b8583ed57a30bcad1552abdb0876941464/examples/MLP/MLP.cpp#L40) in a debugger, the `y1` variable is initialized correctly, i.e., `y1._expr._lhs._vec` displays correctly on the debugger. But as soon as I move over to line 41, which has nothing to do with the y1 variable (It just constructs the `Layer` object), `y1._expr._lhs._vec` is filled with garbage values, and the program no longer behaves correctly. Upon closer inspection, it seems like `y1` is being set to a garbage value immediately after `mgcpp::device_vector`'s move assignment operator is invoked. I am completely stumped. Maybe the code is invoking UB somewhere? I don't have a clue. The problem persists in both clang and gcc.

**Comment by mujjingun** [comment]
Valgrind output seems to be onto something here:
http://lpaste.net/362525

**Comment by Red-Portal** [comment]
This is probably related to a dangling const reference

**Comment by Red-Portal** [comment]
This issue is fixed
