### ISSUE TITLE
Make half precision floating point types work

### ISSUE THREAD

**Issue by Red-Portal** [MGfoundation/mgcpp#4]
Make half precision floating point types work

For some reason half precision CUDA types won't compile.
They are currently commented out waiting for investigation.

**Comment by mujjingun** [comment]
I've discovered that if you #include <cuComplex.h> first and then #include <cuda_fp16.h> then it compiles.

**Comment by Red-Portal** [comment]
@mujjingun I would say that's some weird behavior :S

**Comment by Red-Portal** [comment]
Some CUDA devices with low CUDA computability do not support half precision types.
Identifying those and conditionally compiling half precision operations will be required

**Comment by Red-Portal** [comment]
Not fully functional but it's pretty much now officially supported.
